### PR TITLE
Used mclapply to parallelise the parameter search

### PR DESCRIPTION
**Pull request by NathanSkene**
Split of part of the paramSweep_v3 code into a seperate function so that it could be sent to mclapply rather than iterating through it in a for loop. Just running on my laptop with a couple of cores it halved the run time.

### CODE REVIEW

**Comment by JonathanCruard** [comment]
Hi, parallelization is great indeed, but I'm having trouble with the way you implemented it.
I'm working on a pipeline for scRNAseq analysis and parallelize the preprocess steps across samples (including DoubletFinder).
With your implementation, the problem is that each of my threads will launch n_cores-1 other threads.
It would be great to allow the user to choose between parallelised or sequential processing, or allow to set the maximum number of cores to use.

Do you have any other suggestions to solve this problem?
Thank you.
JonathanCruard

**Comment by NathanSkene** [comment]
Good point Jonathan. I've just created a new pull requests which sets the default mode to sequential and lets the user set the number of cores.

**Comment by JonathanCruard** [comment]
Thank you for the very quick response and reaction.
I will test that, you saved the day.
Have a nice day

**Comment by NathanSkene** [comment]
Dont think the pull request has been approved yet, but I think you should be able to see the pull request & copy the function? If not let me know and I'll send it to you

**Comment by chris-mcginnis-ucsf** [comment]
Sorry for being AWOL -- what is the status of this?

**Pull request merged**
